use std::mem::MaybeUninit;
use std::sync::Arc;
use std::str::FromStr;
use std::fs::File;

use anyhow::anyhow;
use anyhow::{Context, Result};
use clap::Parser;
use daemonize::Daemonize;
use hyper::Uri;
use libbpf_rs::skel::{OpenSkel, SkelBuilder};
use nix::net::if_::if_nametoindex;

#[global_allocator]
static GLOBAL: mimalloc::MiMalloc = mimalloc::MiMalloc;

pub mod access_log;
pub mod access_rules;
pub mod actions;
pub mod config;
pub mod app_state;
pub mod cli;
pub mod content_scanning;
pub mod firewall;
pub mod http_client;
pub mod wirefilter;
pub mod threat;
pub mod redis;
pub mod proxy_protocol;
pub mod authcheck;
pub mod http_proxy;
pub mod bpf {
    // Include the skeleton generated by build.rs into OUT_DIR at compile time
    include!(concat!(env!("OUT_DIR"), "/filter.skel.rs"));
}

pub mod bpf_stats;
pub mod tcp_fingerprint;
pub mod event_queue;
pub mod ja4_plus;
pub mod utils;
pub mod worker;

use tokio::signal;
use tokio::sync::watch;

use crate::app_state::AppState;
use crate::bpf_stats::BpfStatsCollector;
use crate::tcp_fingerprint::TcpFingerprintCollector;
use crate::tcp_fingerprint::TcpFingerprintConfig;
use crate::cli::{Args, Config};
use crate::wirefilter::init_config;
use crate::content_scanning::{init_content_scanner, ContentScanningConfig};
use crate::utils::bpf_utils::{bpf_attach_to_xdp, bpf_detach_from_xdp};

use crate::actions::captcha::{CaptchaConfig, CaptchaProvider, init_captcha_client, start_cache_cleanup_task};
use crate::access_log::{LogSenderConfig, set_log_sender_config};
use crate::event_queue::start_batch_event_processor;
use crate::authcheck::validate_api_key;
use crate::http_client::init_global_client;

fn main() -> Result<()> {

    let args = Args::parse();

    // Validate required arguments when no config file is provided
    if args.config.is_none() {
        if args.upstream.is_none() {
            return Err(anyhow::anyhow!("--upstream is required when no config file is provided"));
        }
        if args.arxignis_api_key.is_none() {
            return Err(anyhow::anyhow!("--arxignis-api-key is required when no config file is provided"));
        }
    }

    // Load configuration
    let config = Config::load_from_args(&args)
        .context("Failed to load configuration")?;

    // Handle daemonization before starting tokio runtime
    if config.daemon.enabled {
        let stdout = File::create(&config.daemon.stdout)
            .with_context(|| format!("Failed to create stdout file: {}", config.daemon.stdout))?;
        let stderr = File::create(&config.daemon.stderr)
            .with_context(|| format!("Failed to create stderr file: {}", config.daemon.stderr))?;

        let mut daemonize = Daemonize::new()
            .pid_file(&config.daemon.pid_file)
            .chown_pid_file(config.daemon.chown_pid_file)
            .working_directory(&config.daemon.working_directory)
            .stdout(stdout)
            .stderr(stderr);

        if let Some(user) = &config.daemon.user {
            daemonize = daemonize.user(user.as_str());
        }

        if let Some(group) = &config.daemon.group {
            daemonize = daemonize.group(group.as_str());
        }

        match daemonize.start() {
            Ok(_) => {
                // We're now in the daemon process, continue with application startup
            }
            Err(e) => {
                eprintln!("Failed to daemonize: {}", e);
                return Err(anyhow::anyhow!("Daemonization failed: {}", e));
            }
        }
    }

    // Initialize logger using CLI level
    // Note: env_logger writes to stderr by default, which is standard practice
    {
        use env_logger::Env;
        let mut builder = env_logger::Builder::from_env(Env::default().default_filter_or("info"));
        builder.filter_level(args.log_level.to_level_filter());
        builder.format_timestamp_secs();

        // In daemon mode, write to stdout instead of stderr for better log separation
        if config.daemon.enabled {
            builder.target(env_logger::Target::Stdout);
        }

        builder.try_init().ok();
    }

    // Start the tokio runtime and run the async application
    tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()?
        .block_on(async_main(args, config))
}

#[allow(clippy::too_many_lines)]
async fn async_main(_args: Args, config: Config) -> Result<()> {

    if config.daemon.enabled {
        log::info!("Running in daemon mode (PID file: {})", config.daemon.pid_file);
    }

    // Initialize global HTTP client with keepalive configuration
    if let Err(e) = init_global_client() {
        log::warn!("Failed to initialize global HTTP client: {}", e);
    } else {
        log::info!("Global HTTP client initialized with keepalive configuration");
    }


    let iface_names: Vec<String> = if !config.network.ifaces.is_empty() {
        config.network.ifaces.clone()
    } else {
        vec![config.network.iface.clone()]
    };

    let mut skels: Vec<Arc<bpf::FilterSkel<'static>>> = Vec::new();
    let mut ifindices: Vec<i32> = Vec::new();

    if config.network.disable_xdp {
        log::info!("XDP disabled by config, skipping BPF attachment");
    } else {
        for iface in iface_names {
            let boxed_open: Box<MaybeUninit<libbpf_rs::OpenObject>> = Box::new(MaybeUninit::uninit());
            let open_object: &'static mut MaybeUninit<libbpf_rs::OpenObject> = Box::leak(boxed_open);
            let skel_builder = bpf::FilterSkelBuilder::default();
            match skel_builder.open(open_object).and_then(|o| o.load()) {
                Ok(mut skel) => {
                    let ifindex = match if_nametoindex(iface.as_str()) {
                        Ok(index) => index as i32,
                        Err(e) => {
                            log::error!("failed to get interface index for '{}': {e}", iface);
                            continue;
                        }
                    };
                    if let Err(e) = bpf_attach_to_xdp(&mut skel, ifindex) {
                        // Check if error is EAFNOSUPPORT (error 97) - IPv6 might be disabled
                        let error_str = e.to_string();
                        if error_str.contains("97") || error_str.contains("Address family not supported") {
                            log::error!("Failed to attach XDP to '{}': {} (IPv6 may be disabled)", iface, e);
                            log::info!("Hint: XDP requires IPv6 kernel support. Try 'sysctl -w net.ipv6.conf.all.disable_ipv6=0' or set 'disable_xdp: true' in config.yaml");
                        } else {
                            log::error!("Failed to attach XDP to '{}': {}", iface, e);
                        }
                        continue;
                    }
                    log::info!("BPF sucessfully attached to xdp on {}", iface);
                    skels.push(Arc::new(skel));
                    ifindices.push(ifindex);
                }
                Err(e) => {
                    log::warn!("failed to load BPF skeleton for '{}': {e}", iface);
                }
            }
        }

        // Initialize access rules immediately after XDP attachment
        if !skels.is_empty() {
            let _ = access_rules::init_access_rules_from_global(&skels);
        }
    }


    // Create BPF statistics collector
    let bpf_stats_collector = BpfStatsCollector::new(skels.clone(), config.bpf_stats.enabled);

    // Create TCP fingerprinting collector
    let tcp_fingerprint_collector = TcpFingerprintCollector::new_with_config(
        skels.clone(),
        TcpFingerprintConfig::from_cli_config(&config.tcp_fingerprint)
    );

    let state = AppState {
        skels: skels.clone(),
        ifindices: ifindices.clone(),
        bpf_stats_collector,
        tcp_fingerprint_collector,
    };

    // Start the old Pingora proxy system in a separate thread (non-blocking)
    std::thread::spawn(|| {
        http_proxy::start::run();
    });

    let (shutdown_tx, shutdown_rx) = watch::channel(false);

    // Initialize Redis manager if Redis URL is provided
    log::info!("Checking Redis configuration: url is_empty={}, tls.mode={}", config.redis.url.is_empty(), config.tls.mode);
    if !config.redis.url.is_empty() {
        log::info!("Initializing Redis manager with URL: {} (prefix: {})", config.redis.url, config.redis.prefix);
        if let Err(e) = redis::RedisManager::init(&config.redis.url, config.redis.prefix.clone()).await {
            log::warn!("Failed to initialize Redis manager: {}", e);
        } else {
            log::info!("Redis manager initialized successfully");
        }
    } else {
        log::warn!("Redis URL is empty, skipping Redis manager initialization");
    }

    // Start certificate fetcher if TLS mode is redis
    log::info!("Checking certificate fetcher conditions: tls.mode={}, redis.url.is_empty={}", config.tls.mode, config.redis.url.is_empty());
    let certificate_fetcher_handle = if config.tls.mode == "redis" && !config.redis.url.is_empty() {
        log::info!("Certificate fetcher conditions met, starting fetcher...");
        // Parse proxy_certificates from config file
        let certificate_path = if let Some(config_path) = &_args.config {
            // Try to read proxy_certificates from config.yaml
            if let Ok(config_content) = std::fs::read_to_string(config_path) {
                if let Ok(yaml) = serde_yaml::from_str::<serde_yaml::Value>(&config_content) {
                    yaml.get("proxy_certificates")
                        .and_then(|v| v.as_str())
                        .map(|s| s.to_string())
                        .unwrap_or_else(|| "/tmp/moat-certs".to_string())
                } else {
                    "/tmp/moat-certs".to_string()
                }
            } else {
                "/tmp/moat-certs".to_string()
            }
        } else {
            "/tmp/moat-certs".to_string()
        };

        let refresh_interval = 300; // 5 minutes default refresh interval
        let shutdown = shutdown_rx.clone();
        log::info!("Starting certificate fetcher for Redis TLS mode (certificate path: {}, refresh interval: {}s). Domains will be read from ssl-storage:domains key in Redis.", certificate_path, refresh_interval);
        Some(worker::certificate::start_certificate_fetcher(certificate_path, refresh_interval, shutdown))
    } else {
        log::warn!("Certificate fetcher not started: tls.mode={}, redis.url.is_empty={}", config.tls.mode, config.redis.url.is_empty());
        None
    };

    // Validate API key if provided
    if !config.arxignis.base_url.is_empty() && !config.arxignis.api_key.is_empty() {
        if let Err(e) = validate_api_key(
            &config.arxignis.base_url,
            &config.arxignis.api_key,
        ).await {
            log::error!("API key validation failed: {}", e);
            return Err(anyhow::anyhow!("API key validation failed: {}", e));
        }
    }

    // Build list of interfaces to attach
    if !config.arxignis.base_url.is_empty() && !config.arxignis.api_key.is_empty() {
        if let Err(e) = init_config(
            config.arxignis.base_url.clone(),
            config.arxignis.api_key.clone(),
        ).await {
            log::warn!("Failed to initialize HTTP filter with config: {}", e);
        }

        // Initialize threat intelligence client
        if let Err(e) = threat::init_threat_client(
            config.arxignis.base_url.clone(),
            config.arxignis.api_key.clone(),
        ).await {
            log::warn!("Failed to initialize threat client: {}", e);
        } else {
            log::info!("Threat intelligence client initialized");
            // Start cache cleanup task
            threat::start_cache_cleanup_task().await;
        }

        // Initialize captcha client if configuration is provided
        if let (Some(site_key), Some(secret_key), Some(jwt_secret)) = (
            &config.arxignis.captcha.site_key,
            &config.arxignis.captcha.secret_key,
            &config.arxignis.captcha.jwt_secret
        ) {
            let captcha_config = CaptchaConfig {
                site_key: site_key.clone(),
                secret_key: secret_key.clone(),
                jwt_secret: jwt_secret.clone(),
                provider: CaptchaProvider::from_str(&config.arxignis.captcha.provider).unwrap_or(CaptchaProvider::HCaptcha),
                token_ttl_seconds: config.arxignis.captcha.token_ttl,
                validation_cache_ttl_seconds: config.arxignis.captcha.cache_ttl,
            };

            if let Err(e) = init_captcha_client(
                captcha_config,
            ).await {
                log::warn!("Failed to initialize captcha client: {}", e);
            } else {
                log::info!("Captcha client initialized with provider: {}", config.arxignis.captcha.provider);
                // Start captcha cache cleanup task
                start_cache_cleanup_task().await;
            }
        } else {
            log::info!("Captcha client not initialized (missing site_key, secret_key, or jwt_secret)");
        }
    } else {
        log::warn!("No API credentials provided, HTTP filter will not be initialized");
    }

    // Initialize content scanning from CLI config
    let content_scanning_config = ContentScanningConfig {
        enabled: config.content_scanning.enabled,
        clamav_server: config.content_scanning.clamav_server.clone(),
        max_file_size: config.content_scanning.max_file_size,
        scan_content_types: config.content_scanning.scan_content_types.clone(),
        skip_extensions: config.content_scanning.skip_extensions.clone(),
        scan_expression: config.content_scanning.scan_expression.clone(),
    };
    if let Err(e) = init_content_scanner(content_scanning_config) {
        log::warn!("Failed to initialize content scanner: {}", e);
    } else {
        log::info!("Content scanner initialized successfully");
    }

    // Initialize access log sender configuration
    let log_sender_config = LogSenderConfig {
        enabled: config.arxignis.log_sending_enabled,
        base_url: config.arxignis.base_url.clone(),
        api_key: config.arxignis.api_key.clone(),
        batch_size_limit: 5000,        // Default: 5000 logs per batch
        batch_size_bytes: 5 * 1024 * 1024, // Default: 5MB
        batch_timeout_secs: 10,        // Default: 10 seconds
        include_response_body: config.arxignis.include_response_body,
        max_body_size: config.arxignis.max_body_size,
    };
    set_log_sender_config(log_sender_config);

    if config.arxignis.log_sending_enabled && !config.arxignis.api_key.is_empty() {
        log::info!("Event sending to arxignis server enabled with unified queue (10s timeout, 5MB limit)");
        // Start the background unified event processor
        start_batch_event_processor();
    } else {
        log::info!("Event sending to arxignis server disabled (enabled: {}, api_key configured: {})",
                   config.arxignis.log_sending_enabled, !config.arxignis.api_key.is_empty());
    }

    // Only parse upstream URI if HTTP server is enabled and upstream is configured
    let _upstream_uri = if !config.server.disable_http_server && !config.server.upstream.is_empty() {
        let parsed = config.server.upstream
            .parse::<Uri>()
            .context("failed to parse upstream URI from config")?;
        if parsed.scheme().is_none() || parsed.authority().is_none() {
            return Err(anyhow!(
                "upstream URI must be absolute (e.g. http://127.0.0.1:8081)",
            ));
        }
        Some(parsed)
    } else {
        None
    };


    // Access rules were already initialized after XDP attachment above

    // Start periodic access rules updater (if BPF is available)
    let access_rules_handle = if !state.skels.is_empty() {
        let skels = state.skels.clone();
        let api_key = config.arxignis.api_key.clone();
        let base_url = config.arxignis.base_url.clone();
        let shutdown = shutdown_rx.clone();
        Some(access_rules::start_access_rules_updater(base_url, skels, api_key, shutdown))
    } else {
        log::info!("Skipping access rules updater (XDP disabled)");
        None
    };

    // Start BPF statistics logging task
    let bpf_stats_handle = if config.bpf_stats.enabled && !state.skels.is_empty() {
        let collector = state.bpf_stats_collector.clone();
        let log_interval = config.bpf_stats.log_interval_secs;
        let shutdown = shutdown_rx.clone();
        Some(start_bpf_stats_logging(collector, log_interval, shutdown))
    } else {
        log::info!("Skipping BPF statistics logging (disabled or XDP not available)");
        None
    };

    // Start dropped IP events logging task
    let dropped_ip_events_handle = if config.bpf_stats.enabled &&
                                       config.bpf_stats.enable_dropped_ip_events &&
                                       !state.skels.is_empty() {
        let collector = state.bpf_stats_collector.clone();
        let log_interval = config.bpf_stats.dropped_ip_events_interval_secs;
        let shutdown = shutdown_rx.clone();
        Some(start_dropped_ip_events_logging(collector, log_interval, shutdown))
    } else {
        log::info!("Skipping dropped IP events logging (disabled or XDP not available)");
        None
    };

    // Start TCP fingerprinting statistics logging task
    let tcp_fingerprint_stats_handle = if config.tcp_fingerprint.enabled && !state.skels.is_empty() {
        let collector = state.tcp_fingerprint_collector.clone();
        let log_interval = config.tcp_fingerprint.log_interval_secs;
        let shutdown = shutdown_rx.clone();
        let state_clone = Arc::new(state.clone());
        Some(start_tcp_fingerprint_stats_logging(collector, log_interval, shutdown, state_clone))
    } else {
        log::info!("Skipping TCP fingerprinting statistics logging (disabled or XDP not available)");
        None
    };

    // Start TCP fingerprinting events logging task
    let tcp_fingerprint_events_handle = if config.tcp_fingerprint.enabled &&
                                           config.tcp_fingerprint.enable_fingerprint_events &&
                                           !state.skels.is_empty() {
        let collector = state.tcp_fingerprint_collector.clone();
        let log_interval = config.tcp_fingerprint.fingerprint_events_interval_secs;
        let shutdown = shutdown_rx.clone();
        let state_clone = Arc::new(state.clone());
        Some(start_tcp_fingerprint_events_logging(collector, log_interval, shutdown, state_clone))
    } else {
        log::info!("Skipping TCP fingerprinting events logging (disabled or XDP not available)");
        None
    };


    signal::ctrl_c().await?;
    log::info!("Shutdown signal received, stopping servers...");
    let _ = shutdown_tx.send(true);

    if let Some(handle) = access_rules_handle
        && let Err(err) = handle.await
    {
        log::error!("access-rules task join error: {err}");
    }

    if let Some(handle) = bpf_stats_handle
        && let Err(err) = handle.await
    {
        log::error!("bpf-stats task join error: {err}");
    }

    if let Some(handle) = dropped_ip_events_handle
        && let Err(err) = handle.await
    {
        log::error!("dropped-ip-events task join error: {err}");
    }

    if let Some(handle) = tcp_fingerprint_stats_handle
        && let Err(err) = handle.await
    {
        log::error!("tcp-fingerprint-stats task join error: {err}");
    }

    if let Some(handle) = tcp_fingerprint_events_handle
        && let Err(err) = handle.await
    {
        log::error!("tcp-fingerprint-events task join error: {err}");
    }

    if let Some(handle) = certificate_fetcher_handle
        && let Err(err) = handle.await
    {
        log::error!("certificate-fetcher task join error: {err}");
    }

    // Detach XDP programs from interfaces
    if !ifindices.is_empty() {
        log::info!("Detaching XDP programs from {} interfaces...", ifindices.len());
        for ifindex in ifindices {
            if let Err(e) = bpf_detach_from_xdp(ifindex) {
                log::error!("Failed to detach XDP from interface {}: {}", ifindex, e);
            }
        }
    }

    Ok(())
}

/// Start a background task that logs BPF statistics periodically
fn start_bpf_stats_logging(
    collector: BpfStatsCollector,
    log_interval_secs: u64,
    mut shutdown: tokio::sync::watch::Receiver<bool>,
) -> tokio::task::JoinHandle<()> {
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(tokio::time::Duration::from_secs(log_interval_secs));

        loop {
            tokio::select! {
                _ = shutdown.changed() => {
                    if *shutdown.borrow() { break; }
                }
                _ = interval.tick() => {
                    if let Err(e) = collector.log_stats() {
                        log::warn!("Failed to log BPF statistics: {}", e);
                    }
                }
            }
        }

        log::info!("BPF statistics logging task stopped");
    })
}

/// Start a background task that logs dropped IP events periodically
fn start_dropped_ip_events_logging(
    collector: BpfStatsCollector,
    log_interval_secs: u64,
    mut shutdown: tokio::sync::watch::Receiver<bool>,
) -> tokio::task::JoinHandle<()> {
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(tokio::time::Duration::from_secs(log_interval_secs));

        loop {
            tokio::select! {
                _ = shutdown.changed() => {
                    if *shutdown.borrow() { break; }
                }
                _ = interval.tick() => {
                    if let Err(e) = collector.log_dropped_ip_events() {
                        log::warn!("Failed to log dropped IP events: {}", e);
                    }
                }
            }
        }

        log::info!("Dropped IP events logging task stopped");
    })
}

/// Start a background task that logs TCP fingerprinting statistics periodically
fn start_tcp_fingerprint_stats_logging(
    collector: TcpFingerprintCollector,
    log_interval_secs: u64,
    mut shutdown: tokio::sync::watch::Receiver<bool>,
    _state: Arc<AppState>,
) -> tokio::task::JoinHandle<()> {
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(tokio::time::Duration::from_secs(log_interval_secs));

        loop {
            tokio::select! {
                _ = shutdown.changed() => {
                    if *shutdown.borrow() { break; }
                }
                _ = interval.tick() => {
                    if let Err(e) = collector.log_stats() {
                        log::warn!("Failed to log TCP fingerprinting statistics: {}", e);
                    }
                }
            }
        }

        log::info!("TCP fingerprinting statistics logging task stopped");
    })
}

/// Start a background task that logs TCP fingerprinting events periodically
fn start_tcp_fingerprint_events_logging(
    collector: TcpFingerprintCollector,
    log_interval_secs: u64,
    mut shutdown: tokio::sync::watch::Receiver<bool>,
    _state: Arc<AppState>,
) -> tokio::task::JoinHandle<()> {
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(tokio::time::Duration::from_secs(log_interval_secs));

        loop {
            tokio::select! {
                _ = shutdown.changed() => {
                    if *shutdown.borrow() { break; }
                }
                _ = interval.tick() => {
                    if let Err(e) = collector.log_fingerprint_events() {
                        log::warn!("Failed to log TCP fingerprinting events: {}", e);
                    }
                }
            }
        }

        log::info!("TCP fingerprinting events logging task stopped");
    })
}
